databases:
- name: webby-database
  plan: free
services:
- type: web
  name: webby
  runtime: ruby
  plan: free
  region: oregon
  buildCommand: "./bin/render-build.sh"

  startCommand: "bundle exec rails server"
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: webby-database
        property: connectionString
    - key: RAILS_ENV
      value: production
    - key: RAILS_MASTER_KEY
      sync: false
    - key: WEB_CONCURRENCY
      value: 2 # sensible default